global:
  scrape_interval: 30s
  scrape_timeout: 30s

scrape_configs:
  - job_name: "snmp"
    static_configs:
      - 192.0.2.1
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

